FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends default-jre-headless && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements-spark.txt .
RUN pip install --no-cache-dir -r requirements-spark.txt
COPY spark_jobs ./spark_jobs
COPY sql ./sql
ENV PYTHONPATH=/app/spark_jobs
ENTRYPOINT ["spark-submit"]
